/**
 * Import pipeline types.
 *
 * RawListingInput  — shape of records coming in from an external source (JSON, CSV row, etc.)
 * NormalizedListing — cleaned and resolved record ready to write to Payload
 * ImportResult     — per-record outcome reported back to the runner
 * ImportSummary    — totals for a full import run
 */

// ─── Raw Input ────────────────────────────────────────────────────────────────

/**
 * Flexible input type. All fields optional except `name`.
 * The pipeline normalizes and validates before writing to Payload.
 */
export type RawListingInput = {
  name: string

  // Location
  citySlug?: string
  regionSlug?: string
  address?: string
  latitude?: number | string | null
  longitude?: number | string | null

  // Classification
  categorySlugs?: string[]

  // Content
  summary?: string
  description?: string
  websiteUrl?: string
  phone?: string

  // Attributes
  attributes?: string[]
  amenities?: string[]
  priceRange?: string
  seasonality?: string

  // SEO
  seoTitle?: string
  seoDescription?: string

  // Provenance — may be present in source data
  sourceId?: string       // ID or key from the external source
  sourceUrl?: string      // Direct URL in the source system if available
}

// ─── Normalized ───────────────────────────────────────────────────────────────

/**
 * Record after normalization and relation resolution.
 * City/region/category IDs have been resolved from slugs.
 */
export type NormalizedListing = {
  name: string
  slug: string

  cityId: string | number
  regionId: string | number
  categoryIds: (string | number)[]

  summary: string
  description: string
  address: string
  latitude: number
  longitude: number

  websiteUrl: string
  phone: string

  attributes: { attribute: string }[]
  amenities: { amenity: string }[]
  priceRange: string
  seasonality: string

  seoTitle: string
  seoDescription: string
}

// ─── Import Result ────────────────────────────────────────────────────────────

export type ImportOutcome = 'created' | 'skipped_duplicate' | 'error'

export type ImportRecordResult = {
  outcome: ImportOutcome
  rawName: string
  slug: string
  status: 'imported' | 'needsReview'
  flags: string[]
  duplicateOfSlug?: string
  error?: string
}

// ─── Import Run Config ────────────────────────────────────────────────────────

export type ImportRunConfig = {
  /** Human-readable source name stored in importMeta.importSource, e.g. "yelp-export-2024-06" */
  importSource: string
  /** Unique batch ID (auto-generated by runner if not provided) */
  importBatch?: string
  /** Path to the JSON file containing RawListingInput[] */
  inputFilePath: string
  /** When true, log each record result to stdout */
  verbose?: boolean
}

// ─── Summary ──────────────────────────────────────────────────────────────────

export type ImportSummary = {
  importBatch: string
  importSource: string
  total: number
  created: number
  skippedDuplicates: number
  errors: number
  needsReview: number
  results: ImportRecordResult[]
}
