/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    regions: Region;
    cities: City;
    listingCategories: ListingCategory;
    listings: Listing;
    guides: Guide;
    events: Event;
    itineraries: Itinerary;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    regions: RegionsSelect<false> | RegionsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    listingCategories: ListingCategoriesSelect<false> | ListingCategoriesSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    itineraries: ItinerariesSelect<false> | ItinerariesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  summary: string;
  heroImage: number | Media;
  intro: string;
  seoTitle: string;
  seoDescription: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    'hero-sm'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'hero-md'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'hero-lg'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'card-sm'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  region: number | Region;
  heroImage: number | Media;
  summary: string;
  intro: string;
  whyVisit: string;
  whenToGo: string;
  featuredHighlights: {
    highlight: string;
    id?: string | null;
  }[];
  latitude: number;
  longitude: number;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Workflow: Draft -> Published (or Archived).
   */
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listingCategories".
 */
export interface ListingCategory {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  description: string;
  /**
   * Choose a stable icon token used by the web app icon renderer.
   */
  icon:
    | 'hotel'
    | 'bed'
    | 'campground'
    | 'rv'
    | 'home'
    | 'restaurant'
    | 'beach'
    | 'whale'
    | 'hiking'
    | 'tidepool'
    | 'family';
  seoTitle: string;
  seoDescription: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  city: number | City;
  region: number | Region;
  categories?: (number | ListingCategory)[] | null;
  summary: string;
  description: string;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  address: string;
  latitude: number;
  longitude: number;
  websiteUrl?: string | null;
  phone?: string | null;
  attributes?:
    | {
        attribute: string;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        amenity: string;
        id?: string | null;
      }[]
    | null;
  priceRange?: string | null;
  seasonality?: string | null;
  editorNotes?: string | null;
  sourceType: 'manual' | 'imported' | 'partner';
  /**
   * Workflow: Draft -> Imported/Needs Review -> Approved -> Published (or Archived).
   */
  status: 'draft' | 'imported' | 'needsReview' | 'approved' | 'published' | 'archived';
  seoTitle: string;
  seoDescription: string;
  /**
   * Populated automatically by the import pipeline. Do not edit manually unless correcting provenance.
   */
  importMeta?: {
    /**
     * Identifier for the source dataset or batch (e.g. "yelp-export-2024-06", "manual-csv-batch-001").
     */
    importSource?: string | null;
    /**
     * Unique batch ID assigned at run time. Groups all records from the same import run.
     */
    importBatch?: string | null;
    importedAt?: string | null;
    /**
     * Name as it appeared in the source data before normalization.
     */
    rawName?: string | null;
    /**
     * Address as it appeared in the source data before normalization.
     */
    rawAddress?: string | null;
    /**
     * Missing or suspicious fields flagged during import. Clear each flag after the field is corrected.
     */
    flags?:
      | {
          flag: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Set by the import pipeline when a probable duplicate was found in the database.
     */
    duplicateSuspected?: boolean | null;
    /**
     * Slug of the existing listing this record may duplicate. Verify before approving.
     */
    duplicateOfSlug?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  heroImage: number | Media;
  excerpt: string;
  body: string;
  relatedCities?: (number | City)[] | null;
  relatedCategories?: (number | ListingCategory)[] | null;
  travelSeason: string;
  seoTitle: string;
  seoDescription: string;
  /**
   * Workflow: Draft -> Review -> Published (or Archived).
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  city: number | City;
  region: number | Region;
  startDate: string;
  endDate?: string | null;
  venue: string;
  summary: string;
  description: string;
  heroImage: number | Media;
  eventUrl?: string | null;
  /**
   * Workflow: Draft -> Review -> Published (or Archived).
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  seoTitle: string;
  seoDescription: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries".
 */
export interface Itinerary {
  id: number;
  title: string;
  /**
   * Auto-generated from the title/name if left blank.
   */
  slug: string;
  summary: string;
  heroImage: number | Media;
  tripLength: string;
  stops: (number | Listing)[];
  body: string;
  relatedCities?: (number | City)[] | null;
  /**
   * Workflow: Draft -> Review -> Published (or Archived).
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  seoTitle: string;
  seoDescription: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'listingCategories';
        value: number | ListingCategory;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'itineraries';
        value: number | Itinerary;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  heroImage?: T;
  intro?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  heroImage?: T;
  summary?: T;
  intro?: T;
  whyVisit?: T;
  whenToGo?: T;
  featuredHighlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listingCategories_select".
 */
export interface ListingCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  region?: T;
  categories?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  gallery?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  websiteUrl?: T;
  phone?: T;
  attributes?:
    | T
    | {
        attribute?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        amenity?: T;
        id?: T;
      };
  priceRange?: T;
  seasonality?: T;
  editorNotes?: T;
  sourceType?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  importMeta?:
    | T
    | {
        importSource?: T;
        importBatch?: T;
        importedAt?: T;
        rawName?: T;
        rawAddress?: T;
        flags?:
          | T
          | {
              flag?: T;
              id?: T;
            };
        duplicateSuspected?: T;
        duplicateOfSlug?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  body?: T;
  relatedCities?: T;
  relatedCategories?: T;
  travelSeason?: T;
  seoTitle?: T;
  seoDescription?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  region?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  eventUrl?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries_select".
 */
export interface ItinerariesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  heroImage?: T;
  tripLength?: T;
  stops?: T;
  body?: T;
  relatedCities?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        'hero-sm'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'hero-md'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'hero-lg'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'card-sm'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline: string;
  defaultSeo: {
    title: string;
    description: string;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contact: {
    email: string;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Background image for the homepage hero section. If set, this overrides the image pulled from featured cities.
   */
  heroImage?: (number | null) | Media;
  heroHeadline: string;
  heroSubheadline: string;
  heroCta: {
    label: string;
    url: string;
  };
  featuredCities?: (number | City)[] | null;
  featuredCategories?: (number | ListingCategory)[] | null;
  editorialIntroBlock: {
    headline: string;
    body: string;
  };
  utilityTeaserBlock: {
    headline: string;
    body: string;
  };
  planningCtaBlock: {
    headline: string;
    body: string;
    buttonLabel: string;
    buttonUrl: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  headerNavItems?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerActionButtons?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerNavGroups?:
    | {
        groupLabel: string;
        links: {
          label: string;
          url: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footerNavGroups?:
    | {
        groupLabel: string;
        links: {
          label: string;
          url: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroImage?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  featuredCities?: T;
  featuredCategories?: T;
  editorialIntroBlock?:
    | T
    | {
        headline?: T;
        body?: T;
      };
  utilityTeaserBlock?:
    | T
    | {
        headline?: T;
        body?: T;
      };
  planningCtaBlock?:
    | T
    | {
        headline?: T;
        body?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  headerNavItems?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  headerActionButtons?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerNavGroups?:
    | T
    | {
        groupLabel?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerNavGroups?:
    | T
    | {
        groupLabel?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}